import{useEffect,useMemo,useRef,useState}from'react';import{supabase}from'../lib/supabase';import{useAuth}from'../context/AuthContext';import{useTeam}from'../context/TeamContext';

const EMOJIS=['👍','❤️','😂','🎉','🔥','👏','💯'];
export default function Chat(){
 const{user}=useAuth(),{team,members}=useTeam();const[messages,setMessages]=useState([]),[text,setText]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[search,setSearch]=useState(''),[online,setOnline]=useState([]),[pinned,setPinned]=useState(null),[emojiFor,setEmojiFor]=useState(null),[editing,setEditing]=useState(null),[unread,setUnread]=useState(0);const bottom=useRef(null),atBottom=useRef(true),initialLoad=useRef(true),reactionRef=useRef(null);
 const names=useMemo(()=>Object.fromEntries((members||[]).map(m=>[m.user_id,m.profiles?.display_name||'Member'])),[members]);
 async function load(){if(!team?.id)return;const wasAtBottom=atBottom.current||initialLoad.current;const{data,error}=await supabase.from('team_chat_messages').select('id,team_id,user_id,content,edited_at,deleted_at,pinned_at,pinned_by,created_at,team_chat_reactions(message_id,user_id,emoji)').eq('team_id',team.id).order('created_at',{ascending:true}).limit(500);if(!error){setMessages(data||[]);if(wasAtBottom)requestAnimationFrame(()=>bottom.current?.scrollIntoView({behavior:'instant',block:'end'}));else setUnread(n=>n+1)}setLoading(false);initialLoad.current=false}
 useEffect(()=>{setMessages([]);setUnread(0);setPinned(null);setEmojiFor(null);setEditing(null);initialLoad.current=true;atBottom.current=true;load();if(!team?.id)return;const channel=supabase.channel('team-chat-'+team.id).on('postgres_changes',{event:'*',schema:'public',table:'team_chat_messages',filter:'team_id=eq.'+team.id},()=>load()).on('postgres_changes',{event:'*',schema:'public',table:'team_chat_reactions'},p=>{if(p.new?.message_id||p.old?.message_id)load()}).on('presence',{event:'sync'},()=>{const state=channel.presenceState();setOnline(Object.values(state).flat().map(x=>x.user_id))}).subscribe(async status=>{if(status==='SUBSCRIBED')await channel.track({user_id:user.id})});return()=>{supabase.removeChannel(channel)}},[team?.id,user?.id]);
 useEffect(()=>{if(atBottom.current)bottom.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages.length]);
 useEffect(()=>{const close=e=>{if(!e.target.closest('.reaction-popover')&&!e.target.closest('.react-trigger'))setEmojiFor(null)};document.addEventListener('click',close);return()=>document.removeEventListener('click',close)},[]);
 const filtered=messages.filter(m=>!search||m.content.toLowerCase().includes(search.toLowerCase())||names[m.user_id]?.toLowerCase().includes(search.toLowerCase()));
 const send=async()=>{const value=text.trim();if(!value||!team||sending)return;setSending(true);if(editing){const{error}=await supabase.from('team_chat_messages').update({content:value,edited_at:new Date().toISOString()}).eq('id',editing);if(error)alert(error.message);else{setEditing(null);setText('')}}else{const{error}=await supabase.from('team_chat_messages').insert({team_id:team.id,user_id:user.id,content:value});if(error)alert(error.message);else setText('')}setSending(false)};
 const react=async(m,e)=>{const mine=(m.team_chat_reactions||[]).some(r=>r.user_id===user.id&&r.emoji===e);if(mine)await supabase.from('team_chat_reactions').delete().match({message_id:m.id,user_id:user.id,emoji:e});else await supabase.from('team_chat_reactions').insert({message_id:m.id,user_id:user.id,emoji:e});setEmojiFor(null)};
 const remove=async m=>{if(!confirm('Delete this message?'))return;await supabase.from('team_chat_messages').update({deleted_at:new Date().toISOString(),content:''}).eq('id',m.id)};
 const pin=async m=>{await supabase.from('team_chat_messages').update({pinned_at:m.pinned_at?null:new Date().toISOString(),pinned_by:m.pinned_at?null:user.id}).eq('id',m.id)};
 const fmt=d=>new Date(d).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
 return <div className="page chat-page"><header><div><p className="eyebrow">TEAM SPACE</p><h1>{team?.name||'Team'} Chat</h1><p className="muted">One shared conversation for everyone in this team. No DMs.</p></div><div className="chat-online"><span/> {online.length||1} online</div></header>
 <section className="chat-shell"><div className="chat-top"><div><b>💬 Team Chat</b><small>{members.length} members · group conversation</small></div><div className="chat-tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search messages…"/><button className="ghost" onClick={()=>setPinned(pinned?null:messages.filter(x=>x.pinned_at))}>📌</button></div></div>
 {pinned&&<div className="chat-pinned"><b>📌 Pinned messages</b>{(Array.isArray(pinned)?pinned:[pinned]).map(m=><span key={m.id}>{m.content||'Deleted message'}</span>)}</div>}
 <div className="chat-messages" onScroll={e=>{atBottom.current=e.currentTarget.scrollHeight-e.currentTarget.scrollTop-e.currentTarget.clientHeight<80;if(atBottom.current)setUnread(0)}}>{loading?<div className="chat-empty">Loading conversation…</div>:!filtered.length?<div className="chat-empty"><div>💬</div><b>{search?'No messages found':'Start the conversation'}</b><span>{search?'Try another search.':'Say hello to your teammates and start learning together.'}</span></div>:filtered.map((m,i)=>{const mine=m.user_id===user.id,name=names[m.user_id]||'Member';const reactions=Object.entries((m.team_chat_reactions||[]).reduce((a,r)=>(a[r.emoji]=(a[r.emoji]||0)+1,a),{}));return <div className={'chat-message '+(mine?'mine':'')} key={m.id}><div className="chat-avatar">{name[0]?.toUpperCase()}</div><div className="chat-bubble-wrap"><div className="chat-meta"><b>{mine?'You':name}</b><span>{fmt(m.created_at)}{m.edited_at?' · edited':''}</span></div><div className={'chat-bubble '+(m.deleted_at?'deleted':'')}>{m.deleted_at?'Message deleted':m.content}</div>{!m.deleted_at&&<div className="chat-message-actions"><button className="react-trigger" title="React" aria-label="React to message" onClick={e=>{e.stopPropagation();setEmojiFor(emojiFor===m.id?null:m.id)}}>😊</button>{mine&&<button onClick={()=>{setEditing(m.id);setText(m.content)}}>Edit</button>}<button onClick={()=>pin(m)}>{m.pinned_at?'Unpin':'Pin'}</button>{(mine||['owner','admin'].includes(team?.role))&&<button onClick={()=>remove(m)}>Delete</button>}</div>}{emojiFor===m.id&&<div className="reaction-popover" ref={reactionRef} onClick={e=>e.stopPropagation()}>{EMOJIS.map(e=><button key={e} onClick={()=>react(m,e)}>{e}</button>)}</div>}{reactions.length>0&&<div className="reaction-row">{reactions.map(([e,n])=><button key={e} onClick={()=>react(m,e)}>{e} {n}</button>)}</div>}</div></div>})}<div ref={bottom}/></div>
 {unread>0&&<button className="chat-new" onClick={()=>{setUnread(0);bottom.current?.scrollIntoView({behavior:'smooth'})}}>{unread} new messages ↓</button>}
 <div className="chat-composer">{editing&&<div className="editing-bar">Editing message <button onClick={()=>{setEditing(null);setText('')}}>Cancel</button></div>}<textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message your team…  (Enter to send, Shift+Enter for a new line)" maxLength={2000}/><div><span>{text.length}/2000 · No attachments</span><button onClick={send} disabled={sending||!text.trim()}>{sending?'Sending…':editing?'Save':'Send ➤'}</button></div></div></section></div>
}