import{useState}from'react';import{BookOpenText,ArrowRight,Plus,CheckCircle,PlayCircle,DotsThreeVertical,PencilSimple,Trash,GraduationCap}from'@phosphor-icons/react';import{useTeam}from'../context/TeamContext';import{supabase}from'../lib/supabase';import TestSeries from'./TestSeries';
export default function Courses({openCourse,onAddCourse,onStartTest}){const{team,courses,videos,reload,progress}=useTeam(),[editing,setEditing]=useState(null),[form,setForm]=useState({}),admin=['owner','admin'].includes(team?.role);function edit(c){setEditing(c.id);setForm({title:c.title,channel:c.channel||'',url:c.url||''})}async function save(){const{error}=await supabase.from('playlists').update({...form,updated_at:new Date().toISOString()}).eq('id',editing).eq('team_id',team.id);if(error)alert(error.message);else{setEditing(null);await reload()}}async function delCourse(c){if(!confirm('Delete '+c.title+' and all its videos, notes, transcripts and progress?'))return;const{error}=await supabase.from('playlists').delete().eq('id',c.id).eq('team_id',team.id);if(error)alert(error.message);else await reload()}async function delVideo(v){if(!confirm('Delete this video and its related notes, transcript and progress?'))return;const{error}=await supabase.from('playlist_videos').delete().eq('id',v.id);if(error)alert(error.message);else await reload()}return <div className="page courses-page">
 <header className="courses-page-header">
  <div className="courses-heading"><div className="courses-heading-icon"><BookOpenText size={22} weight="duotone"/></div><div><p className="eyebrow">YOUR LEARNING LIBRARY</p><h1>Courses</h1><p className="muted">{team?.name} <span className="dot-sep">·</span> {courses.length} {courses.length===1?'course':'courses'}</p></div></div>
  {admin&&<button className="add-course-cta" onClick={onAddCourse}><span className="add-course-icon"><Plus size={18} weight="bold"/></span><span><b>Add course</b><small>Create a new learning path</small></span><ArrowRight size={18}/></button>}
 </header>
 {courses.length>0&&<div className="courses-summary"><div><span className="summary-icon"><GraduationCap size={18} weight="duotone"/></span><div><b>Keep your momentum going</b><small>Pick up where you left off or explore another course.</small></div></div><span className="summary-count">{courses.length} active {courses.length===1?'course':'courses'}</span></div>}
 <div className="course-grid modern-course-grid">
 {courses.map(c=>{const vs=videos[c.id]||[],done=vs.filter(v=>progress[v.id]?.completed_at).length,pc=Math.round(done/(vs.length||1)*100),current=vs.find(v=>!progress[v.id]?.completed_at)||vs[0];return <section className="section library-course-card" key={c.id}>
   <div className="course-card-top"><div className="course-cover"><BookOpenText size={25} weight="duotone"/><span>{vs.length} {vs.length===1?'lesson':'lessons'}</span></div><div className="course-card-menu">{admin&&<button className="icon-ghost" title="Manage course" onClick={()=>edit(c)}><DotsThreeVertical size={20}/></button>}</div></div>
   <div className="library-course-copy"><p className="eyebrow">COURSE</p><h2>{c.title}</h2><p className="course-channel">{c.channel||'Learning course'}</p></div>
   <div className="course-progress-meta"><span><CheckCircle size={15} weight="fill"/> {done} of {vs.length} completed</span><b>{pc}%</b></div>
   <div className="course-progress-track"><i style={{width:pc+'%'}}/></div>
   <div className="course-card-footer"><button className="course-open-btn" onClick={()=>openCourse(c.id)}>{pc>0&&pc<100?<><PlayCircle size={17} weight="fill"/> Continue learning</>:pc>=100?<><CheckCircle size={17} weight="fill"/> Review course</>:<><ArrowRight size={17}/> Start course</>}</button>{current&&pc<100&&<span className="next-lesson">Next: {current.title}</span>}</div>
   {admin&&<div className="course-manage-bar"><span className="muted">Admin controls</span><div className="actions"><button className="ghost" onClick={()=>edit(c)}><PencilSimple size={15}/> Manage</button><button className="danger" onClick={()=>delCourse(c)}><Trash size={15}/> Delete</button></div></div>}
   {editing===c.id&&<div className="course-editor"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}/><input value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/><div className="actions"><button onClick={save}>Save</button><button className="ghost" onClick={()=>setEditing(null)}>Cancel</button></div><div className="checklist">{vs.map(v=><div className="check-row" key={v.id}><span className="grow">{v.title}</span><button className="danger" onClick={()=>delVideo(v)}>Delete</button></div>)}</div></div>}
 </section>})}
 </div>
 {!courses.length&&<section className="section courses-empty"><div className="empty-icon"><BookOpenText size={28} weight="duotone"/></div><h2>No courses yet</h2><p className="muted">This team doesn't have any courses yet.</p>{admin&&<button onClick={onAddCourse}><Plus size={17}/> Add your first course</button>}</section>}
 {team&&<div className="course-tests"><div className="course-tests-heading"><div><p className="eyebrow">ASSESS YOUR LEARNING</p><h2>Tests & quizzes</h2><p className="muted">Practice and test your understanding without leaving Courses.</p></div><GraduationCap size={28} weight="duotone"/></div><TestSeries courseId={null} standalone onStart={onStartTest}/></div>}
 </div>}