import{ArrowRight,ArrowUpRight,Play, Sparkle,BookOpenText,UsersThree,Trophy,Lightning,Robot,CheckCircle,ChartLineUp,NoteBlank,Target,Fire,StackSimple,Plus,StarFour}from'@phosphor-icons/react';
const features=[
 {icon:BookOpenText,title:'One home for every course',copy:'Keep lessons, playlists, notes and progress together instead of scattered across tabs.',tone:'violet'},
 {icon:Robot,title:'AI that works beside you',copy:'Turn what you are learning into notes, summaries and quick quizzes without breaking focus.',tone:'cyan'},
 {icon:UsersThree,title:'Teams that learn together',copy:'Share courses, goals and momentum with your people — without losing your own progress.',tone:'pink'},
 {icon:Trophy,title:'Progress you can feel',copy:'XP, streaks, milestones and leaderboards make consistency visible and motivating.',tone:'gold'}
];
function MiniAvatar({label,tone}){return <span className={'mini-avatar '+tone}>{label}</span>}
export default function Landing({onAuth}){return <main className="lb-landing">
 <div className="lb-grid"/><div className="lb-blob lb-blob-a"/><div className="lb-blob lb-blob-b"/><div className="lb-blob lb-blob-c"/>
 <nav className="lb-nav"><button className="lb-logo" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><span>Learning</span><b>Beyond</b><i>✦</i></button><div className="lb-nav-links"><a href="#features">Features</a><a href="#workflow">How it works</a><a href="#momentum">Why it feels different</a></div><div className="lb-nav-actions"><button className="lb-nav-login" onClick={()=>onAuth('login')}>Log in</button><button className="lb-nav-cta" onClick={()=>onAuth('signup')}>Start free <ArrowUpRight size={15} weight="bold"/></button></div></nav>
 <section className="lb-hero">
  <div className="lb-hero-copy">
   <div className="lb-eyebrow"><span className="eyebrow-dot"/><Sparkle weight="fill"/> THE LEARNING OS FOR CURIOUS PEOPLE</div>
   <h1>Learn with<br/><em>momentum.</em></h1>
   <p className="lb-hero-lead">A beautiful place to learn, track, compete and grow — with your courses, AI tools, teams and progress finally working together.</p>
   <div className="lb-hero-actions"><button className="lb-btn-primary" onClick={()=>onAuth('signup')}>Start learning free <ArrowRight size={18} weight="bold"/></button><button className="lb-btn-secondary" onClick={()=>document.getElementById('features')?.scrollIntoView({behavior:'smooth'})}><Play size={15} weight="fill"/> See what’s inside</button></div>
   <div className="lb-trust-row"><span><CheckCircle weight="fill"/> Learn at your pace</span><span><CheckCircle weight="fill"/> AI-assisted</span><span><CheckCircle weight="fill"/> Built for teams</span></div>
  </div>
  <div className="lb-hero-stage">
   <div className="stage-ring ring-one"/><div className="stage-ring ring-two"/><div className="stage-spark spark-one">✦</div><div className="stage-spark spark-two">✦</div>
   <div className="lb-dashboard-card">
    <div className="dash-head"><div><small>YOUR LEARNING SPACE</small><h3>Good evening, learner <span>✦</span></h3></div><div className="dash-avatar">LB</div></div>
    <div className="dash-metrics"><div className="metric metric-purple"><span>Weekly XP</span><strong>2,840</strong><small>↗ 18% this week</small></div><div className="metric metric-orange"><span>Streak</span><strong>12 <i>days</i></strong><small>🔥 Keep the chain alive</small></div></div>
    <div className="dash-progress"><div className="dash-row"><span>Continue learning</span><b>72%</b></div><div className="dash-track"><i/></div><div className="dash-course"><div className="course-art"><BookOpenText size={20}/></div><div className="course-copy"><b>Build Better Learning Habits</b><span>Lesson 8 · 14 min left</span></div><button><ArrowRight size={16}/></button></div></div>
    <div className="dash-bottom"><span><Robot size={17}/> AI notes ready</span><span><Trophy size={17}/> +120 XP today</span><span><ChartLineUp size={17}/> 4 lessons</span></div>
   </div>
   <div className="lb-float-card ai-float"><div className="float-icon purple"><Robot size={18}/></div><div><b>AI Learn</b><small>Summarise · Quiz · Notes</small></div><Sparkle weight="fill"/></div>
   <div className="lb-float-card xp-float"><div className="float-icon orange"><Lightning size={18} weight="fill"/></div><div><b>+240 XP</b><small>Daily goal complete</small></div><Fire weight="fill"/></div>
   <div className="lb-float-card team-float"><div className="avatar-stack"><MiniAvatar label="A" tone="a"/><MiniAvatar label="R" tone="b"/><MiniAvatar label="S" tone="c"/></div><div><b>Study squad</b><small>3 friends learning now</small></div></div>
  </div>
 </section>
 <section className="lb-marquee" aria-label="LearningBeyond capabilities"><div><span>LEARN</span><i>✦</i><span>TRACK</span><i>✦</i><span>COLLABORATE</span><i>✦</i><span>COMPETE</span><i>✦</i><span>GROW</span><i>✦</i><span>LEARN</span><i>✦</i><span>TRACK</span></div></section>
 <section className="lb-section" id="features"><div className="lb-section-intro"><div><span className="lb-kicker">EVERYTHING IN ONE FLOW</span><h2>Less friction.<br/><em>More learning.</em></h2></div><p>LearningBeyond is designed around the moment you actually learn: open a course, understand something, make it yours, see the progress and come back tomorrow.</p></div>
  <div className="lb-feature-grid">{features.map((f,i)=>{const Icon=f.icon;return <article className={'lb-feature '+f.tone} key={f.title}><div className="feature-top"><span className="feature-number">0{i+1}</span><div className="feature-icon"><Icon size={22} weight="duotone"/></div></div><h3>{f.title}</h3><p>{f.copy}</p><div className="feature-glow"/>{i===0&&<div className="feature-bars"><i/><i/><i/><i/></div>}{i===1&&<div className="feature-ai-chip"><Sparkle weight="fill"/><span>Explain this simply</span><ArrowRight/></div>}{i===2&&<div className="feature-people"><MiniAvatar label="A" tone="a"/><MiniAvatar label="R" tone="b"/><MiniAvatar label="S" tone="c"/><MiniAvatar label="+5" tone="d"/></div>}{i===3&&<div className="feature-chart"><i/><i/><i/><i/><i/><i/></div>}</article>})}</div>
 </section>
 <section className="lb-workflow" id="workflow"><div className="workflow-copy"><span className="lb-kicker">A SIMPLE LOOP</span><h2>Turn “I should learn”<br/>into <em>“I’m learning.”</em></h2><p>The product gets out of your way and keeps the important things visible.</p><button className="lb-btn-primary compact" onClick={()=>onAuth('signup')}>Build your learning space <ArrowRight size={17}/></button></div><div className="workflow-steps"><div className="workflow-step active"><span>01</span><div><b>Choose</b><small>Pick a course or playlist you want to master.</small></div><BookOpenText/></div><div className="workflow-line"/><div className="workflow-step"><span>02</span><div><b>Learn</b><small>Watch, take notes, ask AI and keep moving.</small></div><NoteBlank/></div><div className="workflow-line"/><div className="workflow-step"><span>03</span><div><b>Grow</b><small>Complete lessons, earn XP and build your streak.</small></div><ChartLineUp/></div></div></section>
 <section className="lb-momentum" id="momentum"><div className="momentum-card"><div className="momentum-copy"><span className="lb-kicker">DESIGNED FOR CONSISTENCY</span><h2>Your progress<br/>should <em>come alive.</em></h2><p>Every small action adds up. LearningBeyond turns completion into visible momentum so your next session always has a reason to start.</p><div className="momentum-points"><span><CheckCircle weight="fill"/> Course progress</span><span><CheckCircle weight="fill"/> XP & streaks</span><span><CheckCircle weight="fill"/> Team goals</span><span><CheckCircle weight="fill"/> Milestones</span></div></div><div className="momentum-visual"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="momentum-core"><Target size={28}/><b>72%</b><small>momentum</small></div><div className="orbit-pill pill-one"><Lightning weight="fill"/> +120 XP</div><div className="orbit-pill pill-two"><Fire weight="fill"/> 12 day streak</div><div className="orbit-pill pill-three"><Trophy weight="fill"/> #04 this week</div></div></div></section>
 <section className="lb-cta"><div className="cta-orb cta-one"/><div className="cta-orb cta-two"/><div className="cta-stars">✦　✧　✦</div><span className="lb-kicker">YOUR NEXT CHAPTER STARTS HERE</span><h2>Make learning<br/><em>your superpower.</em></h2><p>One course. One habit. One more step beyond.</p><button className="lb-btn-light" onClick={()=>onAuth('signup')}>Get started — it’s free <ArrowRight size={18}/></button><small>No credit card. Just curiosity.</small></section>
 <footer className="lb-footer"><button className="lb-logo"><span>Learning</span><b>Beyond</b><i>✦</i></button><p>Learn. Grow. Go beyond.</p><span>© 2026 LearningBeyond</span></footer>
 </main>}