import{ArrowRight,PlayCircle,Sparkle,BookOpenText,UsersThree,Trophy,Lightning,Robot,CheckCircle,ChartLineUp}from'@phosphor-icons/react';
export default function Landing({onAuth}){return <main className="landing">
 <div className="landing-noise"/>
 <nav className="landing-nav"><div className="landing-brand">Learning<span>Beyond</span><i>✦</i></div><div className="landing-nav-links"><a href="#features">Features</a><a href="#how">How it works</a><a href="#experience">Experience</a></div><div className="landing-nav-actions"><button className="landing-login" onClick={()=>onAuth('login')}>Log in</button><button className="landing-signup" onClick={()=>onAuth('signup')}>Get Started <ArrowRight size={15}/></button></div></nav>
 <section className="landing-hero">
  <div className="landing-orb orb-one"/><div className="landing-orb orb-two"/>
  <div className="landing-hero-copy"><div className="landing-pill"><Sparkle size={14} weight="fill"/> THE MODERN LEARNING OS</div><h1>Learn smarter.<br/><span>Grow beyond.</span></h1><p>Turn everyday learning into an engaging journey with courses, AI-powered study tools, teams, XP and a little friendly competition.</p><div className="landing-hero-actions"><button className="landing-primary" onClick={()=>onAuth('signup')}>Start learning free <ArrowRight size={18}/></button><button className="landing-play" onClick={()=>document.getElementById('experience')?.scrollIntoView({behavior:'smooth'})}><PlayCircle size={19}/> Explore the experience</button></div><div className="landing-proof"><span><CheckCircle size={16} weight="fill"/> Learn at your pace</span><span><CheckCircle size={16} weight="fill"/> AI-powered</span><span><CheckCircle size={16} weight="fill"/> Built for teams</span></div></div>
  <div className="landing-visual" id="experience"><div className="visual-glow"/><div className="dashboard-mock"><div className="mock-top"><div><small>LEARNING DASHBOARD</small><b>Good morning, learner ✦</b></div><div className="mock-avatar">LB</div></div><div className="mock-stats"><div><span>XP earned</span><strong>2,840</strong><em>↗ 18% this week</em></div><div><span>Active streak</span><strong>12 days</strong><em>Keep it going 🔥</em></div></div><div className="mock-progress"><div className="mock-progress-head"><span>Continue learning</span><b>72%</b></div><div className="progress-line"><i/></div><div className="mock-course"><div className="mock-course-icon"><BookOpenText size={19}/></div><div><b>Build Better Learning Habits</b><span>Lesson 8 · 14 min left</span></div><button><ArrowRight size={16}/></button></div></div><div className="mock-bottom"><div><Robot size={17}/><span>AI Notes ready</span></div><div><Trophy size={17}/><span>+120 XP today</span></div></div></div><div className="float-card float-ai"><span><Robot size={17}/></span><div><b>AI Learn</b><small>Notes · Summary · Quiz</small></div><i>✦</i></div><div className="float-card float-xp"><Lightning size={17} weight="fill"/><div><b>+240 XP</b><small>Daily goal complete</small></div></div></div>
 </section>
 <section className="landing-strip"><div><strong>One place</strong><span>for everything you learn</span></div><div><BookOpenText/><span>Courses</span></div><div><Robot/><span>AI Learn</span></div><div><UsersThree/><span>Teams</span></div><div><Trophy/><span>Leaderboard</span></div></section>
 <section className="landing-section" id="features"><div className="landing-section-head"><div><span className="landing-kicker">BUILT FOR MOMENTUM</span><h2>Learning should feel<br/><span>rewarding.</span></h2></div><p>Everything you need to turn scattered study sessions into a learning habit you actually want to come back to.</p></div><div className="landing-feature-grid"><article className="feature-card feature-purple"><div className="feature-icon"><BookOpenText size={22}/></div><span>01</span><h3>Your learning library</h3><p>Organize courses, track lessons and always know exactly what to learn next.</p><div className="feature-art"><div/><div/><div/></div></article><article className="feature-card feature-blue"><div className="feature-icon"><Robot size={22}/></div><span>02</span><h3>AI that teaches with you</h3><p>Get bite-sized notes, summaries and quizzes for the video you're learning right now.</p><div className="ai-art"><i>✦</i><b>AI Learn</b><small>Make this easier to remember</small></div></article><article className="feature-card feature-orange"><div className="feature-icon"><Trophy size={22}/></div><span>03</span><h3>Make progress visible</h3><p>Earn XP, build streaks and see your momentum turn into something tangible.</p><div className="bars"><i/><i/><i/><i/><i/><i/></div></article><article className="feature-card feature-green"><div className="feature-icon"><UsersThree size={22}/></div><span>04</span><h3>Learn together</h3><p>Create teams, share goals and keep learning moving with your community.</p><div className="people-art"><i/><i/><i/><i/></div></article></div></section>
 <section className="landing-how" id="how"><div className="how-copy"><span className="landing-kicker">SIMPLE BY DESIGN</span><h2>From “I should learn”<br/>to <span>“I’m learning.”</span></h2><p>LearningBeyond brings the structure, feedback and motivation that makes starting easy — and continuing natural.</p><button className="landing-primary small" onClick={()=>onAuth('signup')}>Create your free account <ArrowRight size={16}/></button></div><div className="how-steps"><div><b>01</b><span><strong>Choose your course</strong><small>Pick something you want to master.</small></span></div><div><b>02</b><span><strong>Learn your way</strong><small>Watch, take notes and use AI when you need it.</small></span></div><div><b>03</b><span><strong>Build momentum</strong><small>Earn XP, complete lessons and keep your streak alive.</small></span></div></div></section>
 <section className="landing-cta"><div className="cta-spark">✦</div><span className="landing-kicker">YOUR NEXT CHAPTER STARTS HERE</span><h2>Make learning<br/><span>your superpower.</span></h2><p>Start with one course. Build one habit. Go beyond what you thought you could learn.</p><button className="landing-primary" onClick={()=>onAuth('signup')}>Get Started — It’s Free <ArrowRight size={18}/></button><small>No credit card required to start.</small></section>
 <footer className="landing-footer"><div className="landing-brand">Learning<span>Beyond</span><i>✦</i></div><p>Learn. Grow. Go beyond.</p><span>© 2026 LearningBeyond</span></footer>
 </main>}