import{useEffect,useMemo,useState}from'react';import{supabase}from'../lib/supabase';

const TABS=[['overview','Overview'],['users','Users'],['teams','Teams'],['admins','Admins']];
const fmt=v=>v?new Date(v).toLocaleString(undefined,{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const initials=v=>String(v||'?').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();
const n=v=>Number(v||0);

export default function Admin(){
 const[d,setD]=useState({profiles:[],teams:[],members:[],history:[],courses:[],videos:[],progress:[],chapters:[],notes:[],bookmarks:[],transcripts:[],tests:[],questions:[],options:[],attempts:[],answers:[],admins:[],chat:[],userControls:[],teamControls:[]});
 const[tab,setTab]=useState('overview'),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[authorized,setAuthorized]=useState(null),[detail,setDetail]=useState(null),[detailTab,setDetailTab]=useState('overview'),[edit,setEdit]=useState(null),[range,setRange]=useState(30);
 const load=async()=>{setBusy(true);const rs=await Promise.all([
  supabase.from('profiles').select('*').order('created_at',{ascending:false}).limit(2000),
  supabase.from('teams').select('*').order('created_at',{ascending:false}).limit(1000),
  supabase.from('team_members').select('*').limit(5000),
  supabase.from('team_membership_history').select('*').order('occurred_at',{ascending:false}).limit(10000),
  supabase.from('playlists').select('*').order('created_at',{ascending:false}).limit(2000),
  supabase.from('playlist_videos').select('*').limit(10000),
  supabase.from('video_progress').select('*').limit(30000),
  supabase.from('video_chapters').select('*').limit(20000),
  supabase.from('video_notes').select('id,playlist_video_id,user_id,created_at,updated_at,position_seconds').limit(10000),
  supabase.from('video_bookmarks').select('*').limit(10000),
  supabase.from('video_transcripts').select('*').limit(10000),
  supabase.from('test_series').select('*').order('created_at',{ascending:false}).limit(2000),
  supabase.from('test_questions').select('*').limit(10000),
  supabase.from('test_options').select('*').limit(40000),
  supabase.from('test_attempts').select('*').order('started_at',{ascending:false}).limit(20000),
  supabase.from('test_answers').select('*').limit(50000),
  supabase.from('platform_admins').select('*').limit(100),
  supabase.from('platform_user_controls').select('*').limit(2000),
  supabase.from('platform_team_controls').select('*').limit(1000),
  supabase.from('team_chat_messages').select('*').order('created_at',{ascending:false}).limit(3000)
 ]);const keys=['profiles','teams','members','history','courses','videos','progress','chapters','notes','bookmarks','transcripts','tests','questions','options','attempts','answers','admins','userControls','teamControls','chat'];const bad=rs.find(x=>x.error);if(bad)setMsg(bad.error.message);const x={};keys.forEach((k,i)=>x[k]=rs[i].data||[]);setD(x);setBusy(false)};
 useEffect(()=>{supabase.rpc('is_platform_admin').then(({data,error})=>{if(error){setAuthorized(false);setMsg(error.message)}else{setAuthorized(Boolean(data));if(data)load();else setMsg('Platform admin access required.')}})},[]);
 const names=useMemo(()=>Object.fromEntries(d.profiles.map(x=>[x.id,x.display_name||'Unnamed user'])),[d.profiles]),teamNames=useMemo(()=>Object.fromEntries(d.teams.map(x=>[x.id,x.name])),[d.teams]),testNames=useMemo(()=>Object.fromEntries(d.tests.map(x=>[x.id,x.title])),[d.tests]),courseNames=useMemo(()=>Object.fromEntries(d.courses.map(x=>[x.id,x.title])),[d.courses]);
 const membersByTeam=useMemo(()=>{const m={};d.members.forEach(x=>(m[x.team_id]??=[]).push(x));return m},[d.members]);
 const videosByCourse=useMemo(()=>{const m={};d.videos.forEach(x=>m[x.playlist_id]=(m[x.playlist_id]||0)+1);return m},[d.videos]);
 const questionsByTest=useMemo(()=>{const m={};d.questions.forEach(x=>m[x.test_id]=(m[x.test_id]||0)+1);return m},[d.questions]);
 const submitted=d.attempts.filter(x=>x.submitted_at),avgScore=submitted.length?Math.round(submitted.reduce((a,x)=>a+n(x.percentage),0)/submitted.length):0;
 const activeCutoff=Date.now()-range*864e5,activeUsers=new Set([...d.progress.filter(x=>new Date(x.updated_at).getTime()>activeCutoff).map(x=>x.user_id),...d.attempts.filter(x=>new Date(x.started_at).getTime()>activeCutoff).map(x=>x.user_id)]).size;
 const completion=d.progress.length?Math.round(d.progress.filter(x=>x.completed_at).length/d.progress.length*100):0,watchedHours=Math.round(d.progress.reduce((a,x)=>a+n(x.watched_seconds),0)/3600*10)/10;
 const filtered=useMemo(()=>{const s=q.toLowerCase();if(tab==='users')return d.profiles.filter(x=>JSON.stringify(x).toLowerCase().includes(s));if(tab==='teams')return d.teams.filter(x=>JSON.stringify(x).toLowerCase().includes(s));return d.admins.filter(x=>JSON.stringify(x).toLowerCase().includes(s))},[tab,q,d]);
 const open=(type,data)=>{setDetail({type,data});setDetailTab('overview')};
 const userControl=async(userId,field,value,reason)=>{setBusy(true);const{error}=await supabase.rpc('admin_set_user_control',{p_user_id:userId,p_field:field,p_value:value,p_reason:reason||null});setBusy(false);if(error)setMsg(error.message);else{setMsg('User control updated.');load()}};
 const teamControl=async(teamId,field,value,reason)=>{setBusy(true);const{error}=await supabase.rpc('admin_set_team_control',{p_team_id:teamId,p_field:field,p_value:value,p_reason:reason||null});setBusy(false);if(error)setMsg(error.message);else{setMsg('Team control updated.');load()}};
 const addMember=async(teamId)=>{const email=window.prompt('Enter the existing user email to add');if(!email)return;setBusy(true);const{error}=await supabase.rpc('admin_add_member_by_email',{p_team_id:teamId,p_email:email,p_role:'member'});setBusy(false);if(error)setMsg(error.message);else{setMsg('Member added.');load()}};
 const removeMember=async(teamId,userId)=>{if(!window.confirm('Remove this member from the team?'))return;setBusy(true);const{error}=await supabase.rpc('admin_remove_member',{p_team_id:teamId,p_user_id:userId});setBusy(false);if(error)setMsg(error.message);else{setMsg('Member removed.');load();if(detail)open('team',teamData)}};
 const changeRole=async(teamId,userId,role)=>{setBusy(true);const{error}=await supabase.rpc('admin_change_member_role',{p_team_id:teamId,p_user_id:userId,p_role:role});setBusy(false);if(error)setMsg(error.message);else{setMsg('Role updated.');load()}};
 const editRecord=(type,x)=>{let patch={};if(type==='user')patch={display_name:x.display_name||'',learning_goal:x.learning_goal||'',bio:x.bio||'',theme:x.theme||'system'};if(type==='team')patch={name:x.name,code:x.code,description:x.description||'',category:x.category||'',visibility:x.visibility||'private'};setEdit({type,id:x.id,patch})};
 const save=async()=>{const table=edit.type==='user'?'profiles':'teams';setBusy(true);const{error}=await supabase.from(table).update(edit.patch).eq('id',edit.id);setBusy(false);if(error)setMsg(error.message);else{setMsg('Saved successfully.');setEdit(null);load()}};
 const teamData=detail?.type==='team'?detail.data:null,userData=detail?.type==='user'?detail.data:null;
 const teamCtl=teamData?(d.teamControls.find(x=>x.team_id===teamData.id)||{}):{};
 const userCtl=userData?(d.userControls.find(x=>x.user_id===userData.id)||{}):{};
 const teamCourses=teamData?d.courses.filter(x=>x.team_id===teamData.id):[],teamTests=teamData?d.tests.filter(x=>x.team_id===teamData.id):[],teamMembers=teamData?(membersByTeam[teamData.id]||[]):[];
 const teamVideoIds=new Set(teamCourses.flatMap(c=>d.videos.filter(v=>v.playlist_id===c.id).map(v=>v.id)));
 const teamProgress=teamData?d.progress.filter(x=>teamVideoIds.has(x.playlist_video_id)) :[],teamAttempts=teamData?d.attempts.filter(a=>teamTests.some(t=>t.id===a.test_id)):[];
 const userTeams=userData?d.members.filter(m=>m.user_id===userData.id):[],userHistory=userData?d.history.filter(h=>h.user_id===userData.id):[],userProgress=userData?d.progress.filter(x=>x.user_id===userData.id):[],userAttempts=userData?d.attempts.filter(x=>x.user_id===userData.id):[],userNotes=userData?d.notes.filter(x=>x.user_id===userData.id):[],userBookmarks=userData?d.bookmarks.filter(x=>x.user_id===userData.id):[];
 const userCompleted=userProgress.filter(x=>x.completed_at).length,userAvg=userAttempts.filter(x=>x.submitted_at).length?Math.round(userAttempts.filter(x=>x.submitted_at).reduce((a,x)=>a+n(x.percentage),0)/userAttempts.filter(x=>x.submitted_at).length):0;
 if(authorized===false)return <section className="page admin-page"><div className="admin-denied"><span>🔒</span><h1>Platform admin access required</h1><p>Your signed-in account is not registered as a platform administrator.</p></div></section>;
 return <section className="page admin-page">
  <header className="admin-hero admin-hero-v3"><div><span className="admin-kicker">LEARNINGBEYOND · PLATFORM OPERATIONS</span><h1>Command <span>Center</span></h1><p>Platform-wide visibility, with deep drill-down into every team and learner.</p><div className="admin-hero-actions"><button onClick={load}>↻ Refresh</button><span>{busy?'Syncing…':'● Live platform data'}</span></div></div><div className="admin-system-card"><span className="admin-live-dot"/>SYSTEM ONLINE<strong>{d.profiles.length} users</strong><small>{d.teams.length} teams · {d.courses.length} courses · {d.tests.length} assessments</small></div></header>
  {msg&&<div className="admin-message">{msg}<button onClick={()=>setMsg('')}>×</button></div>}
  <nav className="admin-tabs">{TABS.map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>{setTab(x[0]);setQ('')}}>{x[1]}</button>)}</nav>
  {tab==='overview'?<div className="admin-overview">
   <div className="admin-stat-grid admin-stat-grid-v3">{[['👥','Users',d.profiles.length,'Registered'],['⚡','Active',activeUsers,'Last '+range+' days'],['◈','Teams',d.teams.length,'Workspaces'],['▣','Courses',d.courses.length,d.videos.length+' videos'],['🧠','Quizzes',d.tests.length,d.tests.filter(x=>x.published).length+' published'],['🎯','Avg score',avgScore+'%',submitted.length+' attempts'],['▶','Watched',watchedHours+'h','Tracked time'],['✓','Completion',completion+'%','Progress records']].map(x=><article className="admin-kpi" key={x[1]}><span>{x[0]}</span><div><small>{x[1]}</small><strong>{x[2]}</strong><em>{x[3]}</em></div></article>)}</div>
   <div className="admin-two-col"><section className="admin-panel"><div className="admin-section-head"><div><span className="admin-eyebrow">TEAM LANDSCAPE</span><h2>Teams at a glance</h2><p>Open a team for its complete operational view.</p></div></div><div className="admin-team-cards">{d.teams.map(t=><button key={t.id} onClick={()=>open('team',t)}><span className="admin-avatar">{initials(t.name)}</span><div><b>{t.name}</b><small>{membersByTeam[t.id]?.length||0} members · {d.courses.filter(c=>c.team_id===t.id).length} courses · {d.tests.filter(x=>x.team_id===t.id).length} quizzes</small></div><strong>→</strong></button>)}</div></section>
   <section className="admin-panel"><div className="admin-section-head"><div><span className="admin-eyebrow">ATTENTION</span><h2>Platform health</h2></div></div><div className="admin-health">{[[d.transcripts.filter(x=>x.status==='error').length,'Failed transcripts'],[d.tests.filter(x=>(questionsByTest[x.id]||0)===0).length,'Empty quizzes'],[d.tests.filter(x=>!x.published).length,'Draft quizzes'],[d.progress.filter(x=>!x.completed_at&&new Date(x.updated_at)<new Date(Date.now()-90*864e5)).length,'Stale progress']].map(x=><div key={x[1]}><span>{x[0]?'!':'✓'}</span><div><b>{x[1]}</b><small>{x[0]?'Needs review':'No issues detected'}</small></div><strong>{x[0]}</strong></div>)}</div></section></div>
  </div>:<div className="admin-panel admin-data-panel">
   <div className="admin-toolbar-v3"><div><span className="admin-eyebrow">{tab.toUpperCase()}</span><h2>{tab==='users'?'User management':tab==='teams'?'Team management':'Platform administrators'}</h2><p>{tab==='users'?'Open a learner to see their complete history, teams, learning, quizzes and activity.':tab==='teams'?'Open a team to inspect members, content, quizzes, performance, activity and health.':'Platform-wide administrators and their roles.'}</p></div><div className="admin-toolbar-tools"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={'Search '+tab+'…'}/><span>{filtered.length} records</span></div></div>
   {tab==='users'&&<div className="admin-records">{filtered.map(x=><div className="admin-record" key={x.id} onClick={()=>open('user',x)}><span className="admin-avatar">{initials(x.display_name)}</span><div className="admin-record-main"><b>{x.display_name||'Unnamed user'}</b><small>{x.learning_goal||'No learning goal'} · Joined {fmt(x.created_at)}</small></div><span className="admin-record-meta">{d.members.filter(m=>m.user_id===x.id).length} teams</span><span className="admin-record-meta">{d.attempts.filter(a=>a.user_id===x.id).length} quizzes</span><button onClick={e=>{e.stopPropagation();editRecord('user',x)}}>Edit</button></div>)}</div>}
   {tab==='teams'&&<div className="admin-records">{filtered.map(x=><div className="admin-record" key={x.id} onClick={()=>open('team',x)}><span className="admin-avatar">{initials(x.name)}</span><div className="admin-record-main"><b>{x.name}</b><small>{x.code} · {membersByTeam[x.id]?.length||0} members · {x.description||'No description'}</small></div><span className="admin-record-meta">{d.courses.filter(c=>c.team_id===x.id).length} courses</span><span className="admin-record-meta">{d.tests.filter(t=>t.team_id===x.id).length} quizzes</span><button onClick={e=>{e.stopPropagation();editRecord('team',x)}}>Edit</button></div>)}</div>}
   {tab==='admins'&&<div className="admin-records">{filtered.map(x=><div className="admin-record" key={x.user_id}><span className="admin-avatar">{initials(names[x.user_id])}</span><div className="admin-record-main"><b>{names[x.user_id]||'Admin'}</b><small>{x.role} · Added {fmt(x.created_at)}</small></div><span className="admin-status on">Active</span></div>)}</div>}
  </div>}
  {detail&&<div className="admin-overlay" onClick={()=>setDetail(null)}><div className="admin-modal admin-deep-modal" onClick={e=>e.stopPropagation()}><button className="admin-detail-close" onClick={()=>setDetail(null)}>×</button>
   {detail.type==='team'&&<><div className="admin-detail-hero"><span className="admin-avatar big">{initials(teamData.name)}</span><div><span className="admin-eyebrow">TEAM CONTROL CENTER</span><h2>{teamData.name}</h2><p>{teamData.description||'No team description'} · {teamData.visibility} · {teamData.code}</p></div></div><div className="admin-detail-tabs">{['overview','members','courses','quizzes','activity','controls'].map(x=><button className={detailTab===x?'active':''} onClick={()=>setDetailTab(x)} key={x}>{x}</button>)}</div>
    {detailTab==='overview'&&<><div className="admin-detail-kpis">{[['Members',teamMembers.length],['Courses',teamCourses.length],['Videos',teamCourses.reduce((a,c)=>a+(videosByCourse[c.id]||0),0)],['Quizzes',teamTests.length],['Attempts',teamAttempts.length],['Avg score',teamAttempts.filter(x=>x.submitted_at).length?Math.round(teamAttempts.filter(x=>x.submitted_at).reduce((a,x)=>a+n(x.percentage),0)/teamAttempts.filter(x=>x.submitted_at).length)+'%':'—'],['Completed lessons',teamProgress.filter(x=>x.completed_at).length],['Notes',teamCourses.reduce((a,c)=>a+d.notes.filter(no=>d.videos.find(v=>v.playlist_id===c.id&&v.id===no.playlist_video_id)).length,0)]].map(x=><div><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div><div className="admin-detail-grid"><div><b>Owner</b><span>{names[teamData.created_by]||'—'}</span></div><div><b>Created</b><span>{fmt(teamData.created_at)}</span></div><div><b>Updated</b><span>{fmt(teamData.updated_at)}</span></div><div><b>Category</b><span>{teamData.category||'—'}</span></div></div></>}
    {detailTab==='controls'&&<div className="admin-control-grid"><div><b>Team controls</b><small>Platform-wide overrides for this team.</small>{[['chat_disabled','Disable team chat'],['learning_disabled','Pause learning'],['quiz_disabled','Disable quizzes'],['member_invites_disabled','Disable member invites']].map(([f,l])=><label key={f}><span>{l}</span><input type="checkbox" checked={Boolean(teamCtl[f])} onChange={e=>teamControl(teamData.id,f,e.target.checked)}/></label>)}<button className="danger-soft" onClick={()=>{if(window.confirm('Disable chat for this team?'))teamControl(teamData.id,'chat_disabled',true,'Superadmin action')}}>Disable chat</button></div><div><b>Team actions</b><small>Administrative actions across this workspace.</small><button onClick={()=>addMember(teamData.id)}>＋ Add member by email</button><button onClick={()=>window.dispatchEvent(new CustomEvent('admin:manage-content',{detail:{teamId:teamData.id}}))}>Manage content</button></div></div>}
    {detailTab==='members'&&<div className="admin-deep-list">{teamMembers.map(m=><button onClick={()=>open('user',d.profiles.find(p=>p.id===m.user_id))} key={m.user_id}><span className="admin-avatar">{initials(names[m.user_id])}</span><div><b>{names[m.user_id]}</b><small>{m.role} · Joined {fmt(m.joined_at)}</small></div><div className="admin-member-actions"><select value={m.role} onClick={e=>e.stopPropagation()} onChange={e=>changeRole(teamData.id,m.user_id,e.target.value)}><option>member</option><option>admin</option><option>owner</option></select><button onClick={e=>{e.stopPropagation();removeMember(teamData.id,m.user_id)}}>Remove</button></div></button>)}</div>}
    {detailTab==='courses'&&<div className="admin-deep-list">{teamCourses.map(c=><div key={c.id}><span className="admin-avatar">▣</span><div><b>{c.title}</b><small>{videosByCourse[c.id]||0} videos · {d.tests.filter(t=>t.playlist_id===c.id).length} quizzes · {c.channel||'No channel'}</small></div><strong>{d.progress.filter(p=>d.videos.filter(v=>v.playlist_id===c.id).some(v=>v.id===p.playlist_video_id)&&p.completed_at).length} completions</strong></div>)}</div>}
    {detailTab==='quizzes'&&<div className="admin-deep-list">{teamTests.map(t=>{const a=teamAttempts.filter(x=>x.test_id===t.id&&x.submitted_at);return <div key={t.id}><span className="admin-avatar">🧠</span><div><b>{t.title}</b><small>{questionsByTest[t.id]||0} questions · {t.max_reattempts} reattempts · {t.published?'Published':'Draft'}</small></div><strong>{a.length} attempts · {a.length?Math.round(a.reduce((s,x)=>s+n(x.percentage),0)/a.length)+'% avg':'—'}</strong></div>})}</div>}
    {detailTab==='activity'&&<div className="admin-deep-list">{teamAttempts.slice(0,50).map(a=><div key={a.id}><span className="admin-avatar">{initials(names[a.user_id])}</span><div><b>{names[a.user_id]}</b><small>{testNames[a.test_id]} · {fmt(a.started_at)}</small></div><strong>{a.submitted_at?n(a.percentage)+'%':'In progress'}</strong></div>)}</div>}
   </>}
   {detail.type==='user'&&<><div className="admin-detail-hero"><span className="admin-avatar big">{initials(userData.display_name)}</span><div><span className="admin-eyebrow">LEARNER 360°</span><h2>{userData.display_name||'Unnamed user'}</h2><p>{userData.learning_goal||'No learning goal'} · Joined {fmt(userData.created_at)}</p></div></div><div className="admin-detail-tabs">{['overview','teams','learning','quizzes','activity','controls'].map(x=><button className={detailTab===x?'active':''} onClick={()=>setDetailTab(x)} key={x}>{x}</button>)}</div>
    {detailTab==='overview'&&<><div className="admin-detail-kpis">{[['Teams',userTeams.length],['Lessons started',userProgress.length],['Lessons completed',userCompleted],['Completion',userProgress.length?Math.round(userCompleted/userProgress.length*100)+'%':'0%'],['Quiz attempts',userAttempts.length],['Avg quiz',userAvg+'%'],['Notes',userNotes.length],['Bookmarks',userBookmarks.length]].map(x=><div><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div><div className="admin-detail-grid"><div><b>Learning goal</b><span>{userData.learning_goal||'—'}</span></div><div><b>Theme</b><span>{userData.theme}</span></div><div><b>Bio</b><span>{userData.bio||'—'}</span></div><div><b>Last profile update</b><span>{fmt(userData.updated_at)}</span></div></div></>}
    {detailTab==='controls'&&<div className="admin-control-grid"><div><b>User restrictions</b><small>These controls override normal learner capabilities.</small>{[['blocked','Block account'],['learning_restricted','Restrict learning'],['quiz_restricted','Restrict quizzes'],['chat_restricted','Restrict chat'],['notes_restricted','Restrict notes']].map(([f,l])=><label key={f}><span>{l}</span><input type="checkbox" checked={Boolean(userCtl[f])} onChange={e=>userControl(userData.id,f,e.target.checked,'Superadmin action')}/></label>)}</div><div><b>Danger zone</b><small>Use with care. Changes are immediate.</small><button className="danger-soft" onClick={()=>userControl(userData.id,'blocked',true,'Blocked by platform admin')}>Block user</button><button onClick={()=>userControl(userData.id,'chat_restricted',true,'Chat restricted by platform admin')}>Restrict chat</button></div></div>}
    {detailTab==='teams'&&<div className="admin-deep-list">{userTeams.map(m=>{const t=d.teams.find(x=>x.id===m.team_id);return <button onClick={()=>open('team',t)} key={m.team_id}><span className="admin-avatar">{initials(t?.name)}</span><div><b>{t?.name||'Team'}</b><small>{m.role} · Joined {fmt(m.joined_at)}</small></div><strong>Open team →</strong></button>})}<h3>Membership history</h3>{userHistory.length?userHistory.map(h=><div key={h.id}><span>{h.action}</span><div><b>{teamNames[h.team_id]||'Team'}</b><small>{h.role} · {fmt(h.occurred_at)}</small></div></div>):<p>No historical membership events were recorded before history tracking was enabled.</p>}</div>}
    {detailTab==='learning'&&<div className="admin-deep-list">{userProgress.slice(0,100).map(p=>{const v=d.videos.find(x=>x.id===p.playlist_video_id),c=v&&d.courses.find(x=>x.id===v.playlist_id);return <div key={p.playlist_video_id}><span className="admin-avatar">▶</span><div><b>{v?.title||'Lesson'}</b><small>{c?.title||'Course'} · {Math.round(n(p.watched_seconds)/60)} min watched · {p.completed_at?'Completed':'In progress'}</small></div><strong>{p.duration_seconds?Math.round(n(p.watched_seconds)/n(p.duration_seconds)*100)+'%':'—'}</strong></div>})}</div>}
    {detailTab==='quizzes'&&<div className="admin-deep-list">{userAttempts.map(a=><div key={a.id}><span className="admin-avatar">🧠</span><div><b>{testNames[a.test_id]||'Assessment'}</b><small>{fmt(a.started_at)} · {a.submitted_at?'Submitted':'In progress'} · {a.duration_seconds?Math.round(a.duration_seconds/60)+' min':'—'}</small></div><strong>{a.submitted_at?n(a.percentage)+'%':'—'}</strong></div>)}</div>}
    {detailTab==='activity'&&<div className="admin-deep-list">{[...userProgress.map(x=>({date:x.updated_at,type:'Learning',text:'Progress updated'})),...userAttempts.map(x=>({date:x.started_at,type:'Quiz',text:testNames[x.test_id]||'Assessment'})),...userNotes.map(x=>({date:x.created_at,type:'Note',text:'Created a note'})),...userBookmarks.map(x=>({date:x.created_at,type:'Bookmark',text:'Saved a bookmark'}))].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,100).map((x,i)=><div key={i}><span>{x.type}</span><div><b>{x.text}</b><small>{fmt(x.date)}</small></div></div>)}</div>}
   </>}
  </div></div>}
  {edit&&<div className="admin-overlay"><div className="admin-modal"><div className="admin-modal-head"><div><span className="admin-eyebrow">EDIT</span><h2>{edit.type}</h2></div><button onClick={()=>setEdit(null)}>×</button></div>{Object.entries(edit.patch).map(([k,v])=><label key={k}>{k.replaceAll('_',' ')}<input value={v??''} onChange={e=>setEdit({...edit,patch:{...edit.patch,[k]:e.target.value}})}/></label>)}<div className="admin-modal-actions"><button className="ghost" onClick={()=>setEdit(null)}>Cancel</button><button onClick={save} disabled={busy}>{busy?'Saving…':'Save changes'}</button></div></div></div>}
 </section>
}