import{useState}from'react';import{useTeam}from'../context/TeamContext';import{supabase}from'../lib/supabase';
export default function Teams(){const{teams,team,switchTeam,reload,members}=useTeam(),[name,setName]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
async function create(){if(!name.trim())return;setBusy(true);setMsg('');const{error}=await supabase.rpc('create_team',{p_name:name.trim()});if(error)setMsg(error.message);else{setName('');await reload();setMsg('Team created.')}setBusy(false)}
async function join(){if(!code.trim())return;setBusy(true);setMsg('');const{error}=await supabase.rpc('join_team_by_code',{p_code:code.trim().toUpperCase()});if(error)setMsg(error.message);else{setCode('');await reload();setMsg('Joined team.')}setBusy(false)}
async function leave(){if(!team||!confirm('Leave '+team.name+'?'))return;const{error}=await supabase.rpc('leave_team',{p_team_id:team.id});if(error)setMsg(error.message);else await reload()}
async function copy(){await navigator.clipboard?.writeText(team?.code||'');setMsg('Invite code copied.')}
async function share(){const url=location.origin+location.pathname+'?join='+encodeURIComponent(team.code);await navigator.clipboard?.writeText(url);setMsg('Share link copied.')}
async function role(userId,role){const{error}=await supabase.rpc('set_team_member_role',{p_team_id:team.id,p_user_id:userId,p_role:role});if(error)setMsg(error.message);else{setMsg('Member role updated.');await reload()}}
return <div className="page"><header><div><p className="eyebrow">WORKSPACES</p><h1>Your teams</h1><p className="muted">Private learning workspaces with shared courses, progress and team activity.</p></div></header>{msg&&<div className="notice">{msg}</div>}
<div className="team-grid">{teams.map(t=><section className={'team-card '+(t.id===team?.id?'active':'')} key={t.id}><div className="team-card-top"><div className="team-icon">{t.name.slice(0,2).toUpperCase()}</div><div className="grow"><h2>{t.name}</h2><p className="muted">{t.role==='owner'?'Owner':t.role==='admin'?'Admin':'Member'}</p></div>{t.id===team?.id&&<span className="pill admin">Current</span>}</div><div className="team-code"><span>Invite code</span><b>{t.code}</b></div><div className="team-card-actions"><button disabled={t.id===team?.id} onClick={()=>switchTeam(t.id)}>{t.id===team?.id?'Current team':'Switch team'}</button></div></section>)}</div>
<div className="team-grid"><section className="form-card"><p className="eyebrow">CREATE</p><h2>Start a workspace</h2><p className="muted">Create a private team and become its owner.</p><div className="actions"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Team name"/><button onClick={create} disabled={busy}>Create team</button></div></section><section className="form-card"><p className="eyebrow">JOIN</p><h2>Join a workspace</h2><p className="muted">Use the invite code shared by your teammate.</p><div className="actions"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="TEAM CODE" maxLength={10}/><button onClick={join} disabled={busy}>Join team</button></div></section></div>
{team&&<section className="section"><div className="section-head"><div><p className="eyebrow">CURRENT TEAM</p><h2>{team.name}</h2><p className="muted">Invite code <b>{team.code}</b></p></div><div className="actions"><button className="ghost" onClick={copy}>Copy code</button><button className="ghost" onClick={share}>Share invite link</button><button className="danger" onClick={leave}>Leave team</button></div></div>
<div className="team-members-list">{members.map(m=><div className="team-member" key={m.user_id}><div className="avatar-dot">{(m.profiles?.display_name||'M')[0].toUpperCase()}</div><div className="grow"><b>{m.profiles?.display_name||'Member'}</b><div className="meta">{m.profiles?.learning_goal||'No learning goal set'}</div></div><span className="pill">{m.role}</span>{team.role==='owner'&&m.user_id!==team.created_by&&<select className="role-select" value={m.role} onChange={e=>role(m.user_id,e.target.value)}><option value="member">Member</option><option value="admin">Admin</option></select>}</div>)}</div></section>}</div>}