import{useEffect,useState}from'react';import{toast}from'../lib/toast';import{useTeam}from'../context/TeamContext';import{supabase}from'../lib/supabase';
export default function Teams(){const{teams,team,switchTeam,reload,members}=useTeam(),[name,setName]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[publicTeams,setPublicTeams]=useState([]),[platformAdmin,setPlatformAdmin]=useState(false),[publicName,setPublicName]=useState(''),[publicDesc,setPublicDesc]=useState(''),[publicCategory,setPublicCategory]=useState('');
 async function loadPublic(){const{data,error}=await supabase.from('teams').select('id,name,code,created_by,created_at,visibility,description,category').eq('visibility','public').order('created_at',{ascending:false});if(error)setMsg(error.message);else setPublicTeams(data||[])}
 useEffect(()=>{loadPublic();supabase.rpc('is_platform_admin').then(({data})=>setPlatformAdmin(!!data))},[]);
 async function create(){if(!name.trim())return;setBusy(true);setMsg('');const{error}=await supabase.rpc('create_team',{p_name:name.trim()});if(error)setMsg(error.message);else{setName('');await reload();setMsg('Private team created.');toast('Your workspace is ready.','success','Team created')}setBusy(false)}
 async function join(){if(!code.trim())return;setBusy(true);setMsg('');const{error}=await supabase.rpc('join_team_by_code',{p_code:code.trim().toUpperCase()});if(error)setMsg(error.message);else{setCode('');await reload();setMsg('Joined team.');toast('You are now a member of the workspace.','success','Joined team')}setBusy(false)}
 async function joinPublic(id){setBusy(true);setMsg('');const{error}=await supabase.rpc('join_public_team',{p_team_id:id});if(error)setMsg(error.message);else{await reload();setMsg('Joined public team.');toast('You are now part of the community.','success','Joined public team');loadPublic()}setBusy(false)}
 async function createPublic(){if(!publicName.trim())return;setBusy(true);setMsg('');const{error}=await supabase.rpc('create_public_team',{p_name:publicName.trim(),p_description:publicDesc.trim()||null,p_category:publicCategory.trim()||null});if(error)setMsg(error.message);else{setPublicName('');setPublicDesc('');setPublicCategory('');setMsg('Public team created.');toast('Your public community is live.','success','Team created');await reload();loadPublic()}setBusy(false)}
 async function leave(){if(!team||!confirm('Leave '+team.name+'?'))return;const{error}=await supabase.rpc('leave_team',{p_team_id:team.id});if(error)setMsg(error.message);else await reload()}
 async function copy(){await navigator.clipboard?.writeText(team?.code||'');setMsg('Invite code copied.')}
 async function share(){const url=location.origin+location.pathname+'?join='+encodeURIComponent(team.code);await navigator.clipboard?.writeText(url);setMsg('Share link copied.')}
 async function role(userId,role){const{error}=await supabase.rpc('set_team_member_role',{p_team_id:team.id,p_user_id:userId,p_role:role});if(error){setMsg(error.message);toast(error.message,'error','Action failed')}else{setMsg('Member role updated.');toast('Member permissions were updated.','success','Role updated');await reload()}}
 return <div className="page"><header><div><p className="eyebrow">WORKSPACES</p><h1>Your teams</h1><p className="muted">Private learning workspaces and public communities built around shared goals.</p></div></header>{msg&&<div className="notice">{msg}</div>}
 <div className="team-grid">{teams.map(t=><section className={'team-card '+(t.id===team?.id?'active':'')} key={t.id}><div className="team-card-top"><div className="team-icon">{t.name.slice(0,2).toUpperCase()}</div><div className="grow"><h2>{t.name}</h2><p className="muted">{t.visibility==='public'?'🌎 Public · ':''}{t.role==='owner'?'Owner':t.role==='admin'?'Admin':'Member'}</p></div>{t.id===team?.id&&<span className="pill admin">Current</span>}</div><div className="team-code"><span>Invite code</span><b>{t.code}</b></div><div className="team-card-actions"><button disabled={t.id===team?.id} onClick={()=>switchTeam(t.id)}>{t.id===team?.id?'Current team':'Switch team'}</button></div></section>)}</div>
 <section className="public-teams-cta"><div><span className="public-orb">🌎</span><div><p className="eyebrow">COMMUNITY</p><h2>Join public teams</h2><p className="muted">Learn with peers who have the same goals. Discover open learning communities and join instantly.</p></div></div><button onClick={()=>document.getElementById('public-team-directory')?.scrollIntoView({behavior:'smooth'})}>Explore teams →</button></section>
 {platformAdmin&&<section className="form-card"><p className="eyebrow">PLATFORM ADMIN</p><h2>Create a public team</h2><p className="muted">Only the platform admin can create public communities. You remain the owner and control their courses and tests.</p><div className="public-admin-grid"><input value={publicName} onChange={e=>setPublicName(e.target.value)} placeholder="Public team name"/><input value={publicCategory} onChange={e=>setPublicCategory(e.target.value)} placeholder="Category, e.g. Python"/><input className="wide-input" value={publicDesc} onChange={e=>setPublicDesc(e.target.value)} placeholder="Short description"/><button onClick={createPublic} disabled={busy}>Create public team</button></div></section>}
 <section id="public-team-directory" className="section"><div className="section-head"><div><p className="eyebrow">OPEN COMMUNITIES</p><h2>Public teams</h2><p className="muted">Join a community and learn together.</p></div><span className="pill">{publicTeams.length} teams</span></div>{!publicTeams.length?<div className="public-empty">No public teams yet.</div>:<div className="public-team-grid">{publicTeams.map(t=>{const joined=teams.some(x=>x.id===t.id);return <article className="public-team-card" key={t.id}><div className="public-team-icon">{t.name.slice(0,2).toUpperCase()}</div><div className="grow"><div className="public-team-title"><h3>{t.name}</h3><span>PUBLIC</span></div><p>{t.description||'A LearningBeyond community for shared learning.'}</p><div className="public-team-meta"><span>🎯 {t.category||'General learning'}</span><span>🔓 Open to join</span></div></div><button disabled={joined||busy} onClick={()=>joinPublic(t.id)}>{joined?'Joined ✓':'Join team'}</button></article>})}</div>}</section>
 <div className="team-grid"><section className="form-card"><p className="eyebrow">CREATE</p><h2>Start a workspace</h2><p className="muted">Create a private team and become its owner.</p><div className="actions"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Team name"/><button onClick={create} disabled={busy}>Create team</button></div></section><section className="form-card"><p className="eyebrow">JOIN</p><h2>Join a workspace</h2><p className="muted">Use the invite code shared by your teammate.</p><div className="actions"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="TEAM CODE" maxLength={10}/><button onClick={join} disabled={busy}>Join team</button></div></section></div>
 {team&&<section className="section"><div className="section-head"><div><p className="eyebrow">CURRENT TEAM</p><h2>{team.name}</h2><p className="muted">Invite code <b>{team.code}</b></p></div><div className="actions"><button className="ghost" onClick={copy}>Copy code</button><button className="ghost" onClick={share}>Share invite link</button><button className="danger" onClick={leave}>Leave team</button></div></div><div className="team-members-list">{members.map(m=><div className="team-member" key={m.user_id}><div className="avatar-dot">{(m.profiles?.display_name||'M')[0].toUpperCase()}</div><div className="grow"><b>{m.profiles?.display_name||'Member'}</b><div className="meta">{m.profiles?.learning_goal||'No learning goal set'}</div></div><span className="pill">{m.role}</span>{team.role==='owner'&&m.user_id!==team.created_by&&<select className="role-select" value={m.role} onChange={e=>role(m.user_id,e.target.value)}><option value="member">Member</option><option value="admin">Admin</option></select>}</div>)}</div></section>}</div>}