import{useEffect,useMemo,useState}from'react';import{supabase}from'../lib/supabase';

export default function TestRunner({testId,onBack}){
 const[data,setData]=useState(null),[answers,setAnswers]=useState({}),[index,setIndex]=useState(0),[result,setResult]=useState(null),[solutions,setSolutions]=useState(null),[leaderboard,setLeaderboard]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[secondsLeft,setSecondsLeft]=useState(null),[started,setStarted]=useState(false);
 useEffect(()=>{(async()=>{const[{data:d,error:e},{data:s,error:se}]=await Promise.all([supabase.rpc('get_test_for_learner',{p_test_id:testId}),supabase.rpc('start_test',{p_test_id:testId})]);if(e||se)setError((e||se).message);else{setData(d);setSecondsLeft(s?.time_limit_minutes?s.time_limit_minutes*60:null);setStarted(true)}setBusy(false)})()},[testId]);
 const count=data?.questions?.length||0,q=data?.questions?.[index],answered=Object.keys(answers).length;
 const formatted=useMemo(()=>{if(secondsLeft==null)return'∞';const m=Math.floor(secondsLeft/60),s=secondsLeft%60;return m+':'+String(s).padStart(2,'0')},[secondsLeft]);
 useEffect(()=>{if(!started||secondsLeft==null||result)return; if(secondsLeft<=0){submit(true);return} const t=setInterval(()=>setSecondsLeft(s=>Math.max(0,s-1)),1000);return()=>clearInterval(t)},[started,secondsLeft,result]);
 async function submit(auto=false){if(busy||result||!data)return;setBusy(true);const payload=data.questions.map(q=>({question_id:q.id,selected_option_id:answers[q.id]||null}));const{data:r,error:e}=await supabase.rpc('submit_test',{p_test_id:testId,p_answers:payload});if(e)setError(e.message);else{setResult({...r,auto_submitted:auto||r.auto_submitted});const sr=await supabase.rpc('get_test_solutions',{p_test_id:testId,p_attempt_id:r.attempt_id});setSolutions(sr.data||[]);const lb=await supabase.rpc('get_test_leaderboard',{p_test_id:testId});setLeaderboard(lb.data||[])}setBusy(false)}
 if(error)return <div className="page"><button className="back" onClick={onBack}>← Back</button><div className="notice bad">{error}</div></div>;
 if(busy&&!data)return <div className="page"><div className="test-loading">Loading assessment…</div></div>;
 if(result)return <div className="page test-result-page"><section className="test-result-hero"><span className="result-orb">✓</span><p className="eyebrow">{result.auto_submitted?'TIME UP · AUTO SUBMITTED':'TEST COMPLETE'}</p><h1>{result.percentage}%</h1><p className="muted">{result.correct_count} of {result.total_questions} correct · {result.score} points</p></section><section className="test-result-panel"><div className="result-tabs"><button className="active">Solutions</button><button onClick={()=>document.querySelector('.test-result-leaderboard')?.scrollIntoView({behavior:'smooth'})}>Leaderboard</button></div><div className="solution-list">{(solutions||[]).map((s,i)=><article className="solution-card" key={s.id}><div className="solution-q"><span>{i+1}</span><b>{s.question}</b></div><div className="solution-options">{(s.options||[]).map(o=><div className={'solution-option '+(o.is_correct?'correct ':'')+(s.selected_option_id===o.id&&!o.is_correct?'wrong':'')} key={o.id}><strong>{String.fromCharCode(65+(o.position||0))}</strong><span>{o.option_text}</span>{o.is_correct&&<em>Correct</em>}{s.selected_option_id===o.id&&!o.is_correct&&<em>Your answer</em>}</div>)}</div>{s.explanation&&<p className="solution-explanation">{s.explanation}</p>}</article>)}</div></section><section className="test-result-leaderboard test-result-panel"><div className="result-section-title"><div><p className="eyebrow">TEAM RESULTS</p><h2>Test leaderboard</h2></div><span className="pill">{(leaderboard||[]).length} attempts</span></div><div className="test-leader-list">{(leaderboard||[]).map((x,i)=><div className="test-leader-row" key={x.user_id}><span className="rank-badge">{i+1}</span><span className="avatar-dot">{(x.display_name||'?')[0].toUpperCase()}</span><div className="grow"><b>{x.display_name}</b><small>{x.correct_count}/{x.total_questions} correct</small></div><strong>{x.percentage}%</strong><span className="muted">{x.score} pts</span></div>)}{!leaderboard?.length&&<div className="test-empty">No submitted attempts yet.</div>}</div></section><button className="back" onClick={onBack}>← Back to course</button></div>;
 return <div className="page test-runner-page"><button className="back" onClick={onBack}>← Back to course</button><header className="test-runner-head"><div><p className="eyebrow">ASSESSMENT · {data.test.title}</p><h1>{q?.question}</h1></div><div className="timer-badge"><span>⏱</span>{formatted}</div></header><div className="test-progress"><i style={{width:((index+1)/(count||1)*100)+'%'}}/></div><div className="question-layout"><aside className="question-map"><div className="question-map-head"><b>Questions</b><span>{answered}/{count}</span></div><div className="question-grid">{data.questions.map((qq,i)=><button key={qq.id} className={answers[qq.id]?'answered':''} onClick={()=>setIndex(i)}>{i+1}</button>)}</div><div className="question-legend"><span><i className="answered-dot"/>Answered</span><span><i/>Unanswered</span></div></aside><section className="question-main"><div className="question-card"><div className="question-meta"><span>Question {index+1} of {count}</span><span>{answered} answered</span></div><h2>{q?.question}</h2><div className="test-options">{(q?.options||[]).map(o=><button key={o.id} className={answers[q.id]===o.id?'selected':''} onClick={()=>setAnswers(a=>({...a,[q.id]:o.id}))}><span className="option-letter">{String.fromCharCode(65+(o.position||0))}</span><span>{o.option_text}</span>{answers[q.id]===o.id&&<b>✓</b>}</button>)}</div></div><div className="test-runner-actions"><span className="muted">{answered}/{count} answered</span><div><button className="ghost" disabled={index===0} onClick={()=>setIndex(index-1)}>← Previous</button>{index<count-1?<button onClick={()=>setIndex(index+1)}>Next →</button>:<button onClick={()=>submit(false)} disabled={busy}>{busy?'Submitting…':'Submit test'}</button>}</div></div></section></div></div>
}