import{useEffect,useMemo,useRef,useState}from'react';import{supabase}from'../lib/supabase';

export default function TestRunner({testId,onBack}){
 const[data,setData]=useState(null),[language,setLanguage]=useState('en'),[answers,setAnswers]=useState({}),[times,setTimes]=useState({}),[index,setIndex]=useState(0),[result,setResult]=useState(null),[solutions,setSolutions]=useState([]),[leaderboard,setLeaderboard]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[secondsLeft,setSecondsLeft]=useState(null),[started,setStarted]=useState(false),[away,setAway]=useState(false),[submitting,setSubmitting]=useState(false);
 const questionStarted=useRef(Date.now()),timesRef=useRef({}),answersRef=useRef({}),locked=!!started&&!result;

 useEffect(()=>{(async()=>{const[{data:d,error:e},{data:s,error:se}]=await Promise.all([supabase.rpc('get_test_for_learner',{p_test_id:testId}),supabase.rpc('start_test',{p_test_id:testId})]);if(e||se)setError((e||se).message);else{setData(d);setLanguage(d?.test?.default_language||'en');const limit=s?.time_limit_minutes?Number(s.time_limit_minutes)*60:null;const elapsed=s?.started_at?Math.max(0,(Date.now()-new Date(s.started_at).getTime())/1000):0;setSecondsLeft(limit==null?null:Math.max(0,Math.ceil(limit-elapsed)));setStarted(true);questionStarted.current=Date.now()}setBusy(false)})()},[testId]);

 useEffect(()=>{if(!started||result||secondsLeft==null)return;if(secondsLeft<=0){submit(true);return}const t=setInterval(()=>setSecondsLeft(s=>Math.max(0,s-1)),1000);return()=>clearInterval(t)},[started,secondsLeft,result]);
 useEffect(()=>{if(!locked)return;const before=e=>{e.preventDefault();e.returnValue='Your test is in progress. Submit the test before leaving.';return e};const pop=()=>{history.pushState({testLock:true},'',location.href);setError('Your test is in progress. Submit the test before leaving.');};history.pushState({testLock:true},'',location.href);window.addEventListener('beforeunload',before);window.addEventListener('popstate',pop);return()=>{window.removeEventListener('beforeunload',before);window.removeEventListener('popstate',pop)}},[locked]);
 useEffect(()=>{if(!locked)return;const visibility=()=>{if(document.hidden)setAway(true)};document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility)},[locked]);

 const count=data?.questions?.length||0,q=data?.questions?.[index],answered=Object.keys(answers).length;
 const displayQuestion=language==='hi'&&q?.question_hi?q.question_hi:q?.question;
 const displayOption=o=>language==='hi'&&o?.option_text_hi?o.option_text_hi:o?.option_text;
 const formatted=useMemo(()=>{if(secondsLeft==null)return'∞';const m=Math.floor(secondsLeft/60),s=secondsLeft%60;return m+':'+String(s).padStart(2,'0')},[secondsLeft]);

 function flushTime(){if(!q)return;const elapsed=Math.max(0,Math.round((Date.now()-questionStarted.current)/1000));if(elapsed){const next={...timesRef.current,[q.id]:(timesRef.current[q.id]||0)+elapsed};timesRef.current=next;setTimes(next)}questionStarted.current=Date.now()}
 function go(i){flushTime();setIndex(i)}
 function selectAnswer(id,oid){flushTime();const next={...answersRef.current,[id]:oid};answersRef.current=next;setAnswers(next)}
 async function submit(auto=false){if(submitting||result||!data)return;flushTime();setSubmitting(true);const payload=data.questions.map(x=>({question_id:x.id,selected_option_id:answersRef.current[x.id]||null,time_spent_seconds:timesRef.current[x.id]||0}));const{data:r,error:e}=await supabase.rpc('submit_test',{p_test_id:testId,p_answers:payload});if(e){setError(e.message);setSubmitting(false);return}setResult({...r,auto_submitted:auto||r.auto_submitted});const sr=await supabase.rpc('get_test_solutions',{p_test_id:testId,p_attempt_id:r.attempt_id});setSolutions(sr.data||[]);const lb=await supabase.rpc('get_test_leaderboard',{p_test_id:testId});setLeaderboard(lb.data||[]);setSubmitting(false)}
 function leave(){if(locked){setError('Finish and submit this test before leaving.');return}onBack()}

 if(error&&!data)return <div className="page"><button className="back" onClick={onBack}>← Back</button><div className="notice bad">{error}</div></div>;
 if(busy&&!data)return <div className="page"><div className="test-loading">Loading assessment…</div></div>;

 if(result)return <div className="page test-result-page"><button className="back" onClick={onBack}>← Back to course</button><section className="test-result-hero"><span className="result-orb">✓</span><p className="eyebrow">{result.auto_submitted?'TIME UP · AUTO SUBMITTED':'TEST COMPLETE'}</p><h1>{result.percentage}%</h1><p className="muted">{result.correct_count} / {result.total_questions} correct · {result.score} points · {Math.floor((result.duration_seconds||0)/60)}m {(result.duration_seconds||0)%60}s</p><div className="result-insight-grid"><div><span>Accuracy</span><strong>{result.percentage}%</strong></div><div><span>Avg / question</span><strong>{result.total_questions?Math.round(result.duration_seconds/result.total_questions):0}s</strong></div><div><span>Questions</span><strong>{result.total_questions}</strong></div><div><span>Points</span><strong>{result.score}</strong></div></div></section><section className="test-result-panel"><div className="result-tabs"><button className="active">Solutions</button><button onClick={()=>document.querySelector('.test-result-leaderboard')?.scrollIntoView({behavior:'smooth'})}>Leaderboard</button></div><div className="solution-list">{solutions.map((s,i)=><article className="solution-card" key={s.id}><div className="solution-q"><span>{i+1}</span><b>{language==='hi'&&s.question_hi?s.question_hi:s.question}</b></div><div className="solution-options">{(s.options||[]).map(o=><div className={'solution-option '+(o.is_correct?'correct ':'')+(s.selected_option_id===o.id&&!o.is_correct?'wrong':'')} key={o.id}><strong>{String.fromCharCode(65+(o.position||0))}</strong><span>{displayOption(o)}</span>{o.is_correct&&<em>Correct</em>}{s.selected_option_id===o.id&&!o.is_correct&&<em>Your answer</em>}</div>)}</div><div className="solution-meta"><span>⏱ {s.time_spent_seconds||0}s spent</span>{s.explanation&&<p>{s.explanation}</p>}</div></article>)}</div></section><section className="test-result-panel test-result-leaderboard"><div className="result-section-title"><div><p className="eyebrow">TEAM RESULTS</p><h2>Test leaderboard</h2><p className="muted">Score first, then completion time.</p></div><span className="pill">{leaderboard.length} attempts</span></div><div className="test-leader-list">{leaderboard.map((x,i)=><div className="test-leader-row" key={x.attempt_id||x.user_id+'-'+i}><span className="rank-badge">{i+1}</span><span className="avatar-dot">{(x.display_name||'?')[0].toUpperCase()}</span><div className="grow"><b>{x.display_name}</b><small>{x.correct_count}/{x.total_questions} correct · {x.average_time_per_question||0}s/question · {Math.floor((x.duration_seconds||0)/60)}m {(x.duration_seconds||0)%60}s</small></div><strong>{x.percentage}%</strong><span className="muted">{x.score} pts</span></div>)}</div></section></div>;

 return <div className="page test-runner-page"><button className="back test-back-locked" onClick={leave}>← Back to course</button><header className="test-runner-head"><div><p className="eyebrow">ASSESSMENT · {data.test.title}</p><h1>{displayQuestion}</h1></div><div className="test-language-switch"><span>Language</span><button className={language==='en'?'active':''} onClick={()=>setLanguage('en')}>English</button><button className={language==='hi'?'active':''} onClick={()=>setLanguage('hi')}>हिन्दी</button></div><div className={'timer-badge '+(secondsLeft!==null&&secondsLeft<=60?'urgent':'')}><span>⏱</span>{formatted}</div></header><div className="test-progress"><i style={{width:((index+1)/(count||1)*100)+'%'}}/></div><div className="test-lock-banner">🔒 Test mode is active · finish and submit before leaving</div><div className="question-layout"><aside className="question-map"><div className="question-map-head"><b>Questions</b><span>{answered}/{count}</span></div><div className="question-grid">{data.questions.map((qq,i)=><button key={qq.id} className={answers[qq.id]?'answered':''} onClick={()=>go(i)}>{i+1}</button>)}</div><div className="question-legend"><span><i className="answered-dot"/>Answered</span><span><i/>Unanswered</span></div></aside><section className="question-main"><div className="question-card"><div className="question-meta"><span>Question {index+1} of {count}</span><span>{answered} answered</span></div><h2>{displayQuestion}</h2><div className="test-options">{(q?.options||[]).map(o=><button key={o.id} className={answers[q.id]===o.id?'selected':''} onClick={()=>selectAnswer(q.id,o.id)}><span className="option-letter">{String.fromCharCode(65+(o.position||0))}</span><span>{displayOption(o)}</span>{answers[q.id]===o.id&&<b>✓</b>}</button>)}</div></div><div className="test-runner-actions"><span className="muted">{answered}/{count} answered</span><div><button className="ghost" disabled={index===0} onClick={()=>go(index-1)}>← Previous</button>{index<count-1?<button onClick={()=>go(index+1)}>Next →</button>:<button onClick={()=>submit(false)} disabled={submitting}>{submitting?'Submitting…':'Submit test'}</button>}</div></div></section></div>{away&&<div className="test-focus-overlay"><div><span>🔒</span><h2>Test paused</h2><p>Please return to this test. Your attempt is still active and you must submit it before leaving.</p><button onClick={()=>setAway(false)}>Return to test</button></div></div>}</div>
}