import{createContext,useContext,useEffect,useRef,useState}from'react';import{onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,updateProfile,updateEmail,updatePassword,sendEmailVerification,sendPasswordResetEmail,verifyPasswordResetCode,confirmPasswordReset,reload}from'firebase/auth';import{firebaseAuth}from'../lib/firebase';import{supabase}from'../lib/supabase';
const C=createContext(null);
function friendlyError(e){const map={'auth/email-already-in-use':'An account already exists with this email.','auth/invalid-email':'Please enter a valid email address.','auth/weak-password':'Password must be at least 6 characters.','auth/invalid-credential':'Email or password is incorrect.','auth/user-not-found':'Email or password is incorrect.','auth/wrong-password':'Email or password is incorrect.','auth/too-many-requests':'Too many attempts. Please wait a moment and try again.','auth/requires-recent-login':'For security, please sign in again before changing this account detail.','auth/expired-action-code':'This password reset link has expired. Please request a new one.','auth/invalid-action-code':'This password reset link is invalid or has already been used.'};return map[e?.code]||e?.message||'Authentication failed. Please try again.'}
function appUserFromSupabase(u){return u?{...u,authSource:'supabase'}:null}
export function AuthProvider({children}){const[user,setUser]=useState(null),[dataUser,setDataUser]=useState(null),[loading,setLoading]=useState(true),[passwordRecovery,setPasswordRecovery]=useState(false),[resetCode,setResetCode]=useState(''),[resetEmail,setResetEmail]=useState('');const syncing=useRef(false);
useEffect(()=>{const params=new URLSearchParams(window.location.search),mode=params.get('mode'),oobCode=params.get('oobCode');if(mode==='resetPassword'&&oobCode){setPasswordRecovery(true);verifyPasswordResetCode(firebaseAuth,oobCode).then(email=>setResetEmail(email)).then(()=>setResetCode(oobCode)).catch(()=>{setResetCode('');setResetEmail('');setPasswordRecovery(true)})}
let alive=true;
async function restore(){const{data,error}=await supabase.auth.getSession();if(!alive)return;if(error||!data?.session?.user){setUser(null);setDataUser(null);setLoading(false);return}const dbUser=data.session.user;setDataUser(dbUser);setUser(firebaseAuth.currentUser||appUserFromSupabase(dbUser));setLoading(false)}
restore();
const unsub=onAuthStateChanged(firebaseAuth,async fu=>{if(!alive)return;const{data}=await supabase.auth.getSession();if(data?.session?.user){setDataUser(data.session.user);setUser(fu||appUserFromSupabase(data.session.user));setLoading(false)}else if(fu&&!syncing.current){await signOut(firebaseAuth);setUser(null);setDataUser(null);setLoading(false)}else if(!fu){setUser(null);setDataUser(null);setLoading(false)}});
return()=>{alive=false;unsub()}},[]);
async function signIn(email,password){const cleanEmail=email.trim().toLowerCase();syncing.current=true;try{
 const legacy=await supabase.auth.signInWithPassword({email:cleanEmail,password});
 if(legacy.error||!legacy.data?.user)throw new Error('Email or password is incorrect.');
 const dbUser=legacy.data.user;setDataUser(dbUser);
 try{const{user:fu}=await signInWithEmailAndPassword(firebaseAuth,cleanEmail,password);await reload(fu);setUser(fu)}catch(firebaseError){
   if(firebaseError?.code==='auth/user-not-found'){try{const{user:fu}=await createUserWithEmailAndPassword(firebaseAuth,cleanEmail,password);if(dbUser.user_metadata?.full_name)await updateProfile(fu,{displayName:dbUser.user_metadata.full_name});await sendEmailVerification(fu);setUser(fu)}catch(e){setUser(appUserFromSupabase(dbUser))}}
   else if(firebaseError?.code==='auth/invalid-credential'||firebaseError?.code==='auth/wrong-password')setUser(appUserFromSupabase(dbUser));
   else setUser(appUserFromSupabase(dbUser));
 }
 setLoading(false);syncing.current=false;return dbUser;
}catch(e){syncing.current=false;throw new Error(e.message||friendlyError(e))}}
async function signUp(email,password,name){const cleanEmail=email.trim().toLowerCase();syncing.current=true;try{const{data:legacy,error:legacyError}=await supabase.auth.signUp({email:cleanEmail,password,options:{data:{full_name:name||''}}});if(legacyError)throw legacyError;if(!legacy?.user)throw new Error('Unable to create your account.');await supabase.auth.signOut();setDataUser(null);setUser(null);try{const{user:fu}=await createUserWithEmailAndPassword(firebaseAuth,cleanEmail,password);if(name)await updateProfile(fu,{displayName:name});await sendEmailVerification(fu);await signOut(firebaseAuth);setUser(null);setDataUser(null)}catch(e){await signOut(firebaseAuth).catch(()=>{});setUser(null);setDataUser(null);throw e}syncing.current=false;return legacy.user}catch(e){syncing.current=false;throw new Error(friendlyError(e))}}
async function logout(){await Promise.allSettled([signOut(firebaseAuth),supabase.auth.signOut()]);setUser(null);setDataUser(null)}
async function resetPassword(email){try{await sendPasswordResetEmail(firebaseAuth,email.trim().toLowerCase(),{url:window.location.origin+'/?mode=resetPassword',handleCodeInApp:true})}catch(e){throw new Error(friendlyError(e))}}
async function updateRecoveredPassword(password){if(!resetCode)throw new Error('This password reset link is invalid or expired. Please request a new one.');try{await confirmPasswordReset(firebaseAuth,resetCode,password);setPasswordRecovery(false);setResetCode('');setResetEmail('');window.history.replaceState({},'',window.location.pathname);return true}catch(e){throw new Error(friendlyError(e))}}
async function updateAccount(changes){try{const u=firebaseAuth.currentUser;if(u){if(changes.displayName!==undefined)await updateProfile(u,{displayName:changes.displayName});if(changes.email&&changes.email!==u.email)await updateEmail(u,changes.email);if(changes.password)await updatePassword(u,changes.password);await reload(u);setUser(firebaseAuth.currentUser)}const dbUser=supabase.auth.getUser();if(changes.displayName!==undefined){const r=await dbUser; if(r.data?.user)await supabase.auth.updateUser({data:{...r.data.user.user_metadata,full_name:changes.displayName}})}}catch(e){throw new Error(friendlyError(e))}}
return <C.Provider value={{user,dataUser,dataUserId:dataUser?.id||null,loading,passwordRecovery,resetEmail,signUp,signIn,logout,resetPassword,updateRecoveredPassword,updateAccount}}>{children}</C.Provider>}export const useAuth=()=>useContext(C);