import { createContext, useContext, useEffect, useRef, useState } from 'react'
import { onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, updateProfile, updateEmail, updatePassword, sendEmailVerification, sendPasswordResetEmail, verifyPasswordResetCode, confirmPasswordReset, reload } from 'firebase/auth'
import { firebaseAuth } from '../lib/firebase'
import { supabase } from '../lib/supabase'

const C=createContext(null);
function friendlyError(e){const map={'auth/email-already-in-use':'An account already exists with this email.','auth/invalid-email':'Please enter a valid email address.','auth/weak-password':'Password must be at least 6 characters.','auth/invalid-credential':'Email or password is incorrect.','auth/user-not-found':'Email or password is incorrect.','auth/wrong-password':'Email or password is incorrect.','auth/too-many-requests':'Too many attempts. Please wait a moment and try again. Please wait and try again later.','auth/network-request-failed':'We could not reach the authentication service. Check your connection and try again.','auth/operation-not-allowed':'Email/password signup is currently disabled. Please contact support.','auth/requires-recent-login':'For security, please sign in again before changing this account detail.','auth/expired-action-code':'This password reset link has expired. Please request a new one.','auth/invalid-action-code':'This password reset link is invalid or has already been used.'};return map[e?.code]||e?.message||'Authentication failed. Please try again.'}
function appUserFromSupabase(u){return u?{...u,authSource:'supabase'}:null}
export function AuthProvider({children}){const[user,setUser]=useState(null),[dataUser,setDataUser]=useState(null),[loading,setLoading]=useState(true),[passwordRecovery,setPasswordRecovery]=useState(false),[resetCode,setResetCode]=useState(''),[resetEmail,setResetEmail]=useState('');const syncing=useRef(false);
useEffect(()=>{const params=new URLSearchParams(window.location.search),mode=params.get('mode'),oobCode=params.get('oobCode');if(mode==='resetPassword'&&oobCode){setPasswordRecovery(true);verifyPasswordResetCode(firebaseAuth,oobCode).then(email=>setResetEmail(email)).then(()=>setResetCode(oobCode)).catch(()=>{setResetCode('');setResetEmail('');setPasswordRecovery(true)})}
let alive=true;
async function getMatchingDataUser(fu){const{data}=await supabase.auth.getSession();const dbUser=data?.session?.user||null;if(!dbUser)return null;const firebaseUid=dbUser.user_metadata?.firebase_uid;const firebaseEmail=(fu?.email||'').trim().toLowerCase();const dbEmail=(dbUser.email||'').trim().toLowerCase();if((firebaseUid&&firebaseUid===fu.uid)||(dbEmail&&dbEmail===firebaseEmail))return dbUser;await supabase.auth.signOut().catch(()=>{});return null}
async function syncFirebaseSession(fu){await reload(fu).catch(()=>{});if(!fu.emailVerified){await signOut(firebaseAuth).catch(()=>{});const dbUser=await getMatchingDataUser(fu);if(dbUser){setDataUser(dbUser);setUser(appUserFromSupabase(dbUser))}else{setUser(null);setDataUser(null)}setLoading(false);return}setUser(fu);const dbUser=await getMatchingDataUser(fu);if(dbUser){setDataUser(dbUser);setLoading(false);return}try{await provisionDataAccount(fu.email||'',fu.displayName||'')}catch(e){setUser(null);setDataUser(null);setLoading(false)}}
async function restore(){const fu=firebaseAuth.currentUser;if(fu){await syncFirebaseSession(fu);return}const{data}=await supabase.auth.getSession();if(!alive)return;if(data?.session?.user){setDataUser(data.session.user);setUser(appUserFromSupabase(data.session.user))}else{setUser(null);setDataUser(null)}setLoading(false)}
restore();
const unsub=onAuthStateChanged(firebaseAuth,async fu=>{if(!alive)return;if(fu)await syncFirebaseSession(fu);else{const{data}=await supabase.auth.getSession();if(!alive)return;if(data?.session?.user){setDataUser(data.session.user);setUser(appUserFromSupabase(data.session.user))}else{setUser(null);setDataUser(null)}setLoading(false)}});
return()=>{alive=false;unsub()}},[]);async function provisionDataAccount(email,displayName,existingOnly=false){const fu=firebaseAuth.currentUser;if(!fu)throw new Error('Your Firebase session is no longer active. Please sign in again.');const token=await fu.getIdToken(true);const{data,error}=await supabase.functions.invoke('provision-firebase-account',{headers:{Authorization:`Bearer ${token}`},body:{email:email.trim().toLowerCase(),displayName:displayName||fu.displayName||'',existingOnly}});const tokenHash=data?.tokenHash;if(!tokenHash)throw new Error(data?.error||error?.message||'We could not open your Learning Beyond data account. Please try again.');const{data:session,error:sessionError}=await supabase.auth.verifyOtp({token_hash:tokenHash,type:'email'});if(sessionError||!session?.user)throw new Error(sessionError?.message||'We could not start your Learning Beyond data session. Please try again.');setDataUser(session.user);setLoading(false);return fu}
async function signIn(email,password){const cleanEmail=email.trim().toLowerCase();if(syncing.current)throw new Error('A sign-in request is already in progress. Please wait a moment.');syncing.current=true;try{try{const{user:fu}=await signInWithEmailAndPassword(firebaseAuth,cleanEmail,password);await reload(fu);if(!fu.emailVerified){const legacy=await supabase.auth.signInWithPassword({email:cleanEmail,password});if(!legacy.error&&legacy.data?.user){await signOut(firebaseAuth).catch(()=>{});const dbUser=legacy.data.user;setDataUser(dbUser);setUser(appUserFromSupabase(dbUser));setLoading(false);return dbUser}try{return await provisionDataAccount(cleanEmail,fu.displayName||'',true)}catch(migrationError){await signOut(firebaseAuth).catch(()=>{});setUser(null);setDataUser(null);const e=new Error('Please verify your email before signing in. Check your inbox for the verification link.');e.code='auth/email-not-verified';throw e}}setUser(fu);return await provisionDataAccount(cleanEmail,fu.displayName||'')}catch(firebaseError){if(firebaseError?.code==='auth/email-not-verified')throw firebaseError;try{const legacy=await supabase.auth.signInWithPassword({email:cleanEmail,password});if(legacy.error||!legacy.data?.user)throw firebaseError;const dbUser=legacy.data.user;setDataUser(dbUser);try{const{user:fu}=await signInWithEmailAndPassword(firebaseAuth,cleanEmail,password);await reload(fu);if(!fu.emailVerified){await signOut(firebaseAuth).catch(()=>{});setUser(appUserFromSupabase(dbUser));setLoading(false);return dbUser}setUser(fu);return await provisionDataAccount(cleanEmail,fu.displayName||dbUser.user_metadata?.full_name||'')}catch(e){if(e?.code==='auth/email-not-verified'){setUser(appUserFromSupabase(dbUser));setLoading(false);return dbUser}if(e?.code==='auth/user-not-found'){try{const{user:fu}=await createUserWithEmailAndPassword(firebaseAuth,cleanEmail,password);if(dbUser.user_metadata?.full_name)await updateProfile(fu,{displayName:dbUser.user_metadata.full_name});await sendEmailVerification(fu);await signOut(firebaseAuth).catch(()=>{});setUser(appUserFromSupabase(dbUser));setLoading(false);return dbUser}catch(createError){if(createError?.code==='auth/email-not-verified'){setUser(appUserFromSupabase(dbUser));setLoading(false);return dbUser}}}else{setUser(appUserFromSupabase(dbUser))}}setLoading(false);return dbUser}catch(legacyError){throw firebaseError}}}catch(e){setLoading(false);throw new Error(friendlyError(e))}finally{syncing.current=false}}
async function signUp(email,password,name){const cleanEmail=email.trim().toLowerCase();if(syncing.current)throw new Error('A signup request is already in progress. Please wait a moment.');syncing.current=true;try{const{user:fu}=await createUserWithEmailAndPassword(firebaseAuth,cleanEmail,password);if(name)await updateProfile(fu,{displayName:name});try{await sendEmailVerification(fu)}catch(verificationError){await signOut(firebaseAuth).catch(()=>{});throw new Error('Your account was created, but we could not send the verification email. Please try signing in again later.')}await signOut(firebaseAuth);setUser(null);setDataUser(null);return fu}catch(e){await signOut(firebaseAuth).catch(()=>{});throw new Error(friendlyError(e))}finally{syncing.current=false}}
async function signInWithGoogle(){syncing.current=true;try{const redirectTo=window.location.origin+'/login';const {data,error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(error)throw error;return data}catch(e){syncing.current=false;throw new Error(e.message||'Google sign-in is unavailable right now.')}}
async function logout(){await Promise.allSettled([signOut(firebaseAuth),supabase.auth.signOut()]);setUser(null);setDataUser(null)}
async function resetPassword(email){const cleanEmail=email.trim().toLowerCase();if(!cleanEmail)throw new Error('Please enter your email address.');try{await sendPasswordResetEmail(firebaseAuth,cleanEmail)}catch(e){throw new Error(friendlyError(e))}}
async function updateRecoveredPassword(password){if(!resetCode)throw new Error('This password reset link is invalid or expired. Please request a new one.');try{await confirmPasswordReset(firebaseAuth,resetCode,password);setPasswordRecovery(false);setResetCode('');setResetEmail('');window.history.replaceState({},'',window.location.pathname);return true}catch(e){throw new Error(friendlyError(e))}}
async function updateAccount(changes){try{const u=firebaseAuth.currentUser;if(u){if(changes.displayName!==undefined)await updateProfile(u,{displayName:changes.displayName});if(changes.email&&changes.email!==u.email)await updateEmail(u,changes.email);if(changes.password)await updatePassword(u,changes.password);await reload(u);setUser(firebaseAuth.currentUser)}const dbUser=supabase.auth.getUser();if(changes.displayName!==undefined){const r=await dbUser;if(r.data?.user)await supabase.auth.updateUser({data:{...r.data.user.user_metadata,full_name:changes.displayName}})}}catch(e){throw new Error(friendlyError(e))}}
return <C.Provider value={{user,dataUser,dataUserId:dataUser?.id||null,loading,passwordRecovery,resetEmail,signUp,signIn,signInWithGoogle,logout,resetPassword,updateRecoveredPassword,updateAccount}}>{children}</C.Provider>}export const useAuth=()=>useContext(C);