import{createContext,useContext,useEffect,useState}from'react';import{onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,updateProfile,updateEmail,updatePassword,sendEmailVerification,reload}from'firebase/auth';import{firebaseAuth}from'../lib/firebase';
const C=createContext(null);
function friendlyError(e){const map={'auth/email-already-in-use':'An account already exists with this email.','auth/invalid-email':'Please enter a valid email address.','auth/weak-password':'Password must be at least 6 characters.','auth/invalid-credential':'Email or password is incorrect.','auth/user-not-found':'Email or password is incorrect.','auth/wrong-password':'Email or password is incorrect.','auth/too-many-requests':'Too many attempts. Please wait a moment and try again.','auth/requires-recent-login':'For security, please sign in again before changing this account detail.'};return map[e?.code]||e?.message||'Authentication failed. Please try again.'}
export function AuthProvider({children}){const[user,setUser]=useState(null),[loading,setLoading]=useState(true),[verificationRequired,setVerificationRequired]=useState(false),[verificationEmail,setVerificationEmail]=useState('');
useEffect(()=>onAuthStateChanged(firebaseAuth,u=>{if(u&&!u.emailVerified){setUser(null);setVerificationRequired(true);setVerificationEmail(u.email||'')}else{setUser(u);setVerificationRequired(false);setVerificationEmail(u?.email||'')}setLoading(false)}),[]);
async function signUp(email,password,name){try{const{user}=await createUserWithEmailAndPassword(firebaseAuth,email,password);if(name)await updateProfile(user,{displayName:name});await sendEmailVerification(user);setVerificationEmail(user.email||email);setVerificationRequired(true);setUser(null);return user}catch(e){throw new Error(friendlyError(e))}}
async function signIn(email,password){try{const{user}=await signInWithEmailAndPassword(firebaseAuth,email,password);await reload(user);if(!user.emailVerified){setVerificationEmail(user.email||email);setVerificationRequired(true);setUser(null);return null}setUser(user);setVerificationRequired(false);return user}catch(e){throw new Error(friendlyError(e))}}
async function checkVerification(){const u=firebaseAuth.currentUser;if(!u){throw new Error('Please sign in again to continue.')}await reload(u);if(!u.emailVerified){throw new Error('Your email is not verified yet. Please click the link in your inbox, then try again.')}setVerificationRequired(false);setVerificationEmail(u.email||'');setUser(u);return u}
async function resendVerification(){const u=firebaseAuth.currentUser;if(!u){throw new Error('Please sign in again to resend the verification email.')}await sendEmailVerification(u);return true}
async function logout(){await signOut(firebaseAuth);setVerificationRequired(false);setVerificationEmail('');setUser(null)}
async function updateAccount(changes){try{const u=firebaseAuth.currentUser;if(!u)throw new Error('You are not signed in.');if(changes.displayName!==undefined)await updateProfile(u,{displayName:changes.displayName});if(changes.email&&changes.email!==u.email)await updateEmail(u,changes.email);if(changes.password)await updatePassword(u,changes.password);await reload(u);setUser(firebaseAuth.currentUser)}catch(e){throw new Error(friendlyError(e))}}
return <C.Provider value={{user,loading,verificationRequired,verificationEmail,signUp,signIn,checkVerification,resendVerification,logout,updateAccount}}>{children}</C.Provider>}
export const useAuth=()=>useContext(C);